apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ include "github-connector-chart.repository" . }}
  labels:
    app: {{ include "github-connector-chart.name" . }}
    chart: {{ include "github-connector-chart.chart" . }}
    release: {{ include "github-connector-chart.release.name" . }}
    heritage: {{ include "github-connector-chart.release.service" . }}
spec:
    gateway: kyma-gateway.kyma-system.svc.cluster.local
    service:
      name: {{ include "github-connector-chart.repository" . }}
      port: {{ .Values.service.port }}
      host: {{ include "github-connector-chart.repository" . }}
    rules:
      - path: /.*
        methods: ["GET", "POST", "PUT"]
        accessStrategies:
          - handler: noop