kind: Service
apiVersion: v1
metadata:
  name: gh-webhook-endpoint
  namespace: gh-connector
  labels:
    app: gh-connector
spec:
  selector:
    app: ghconnector
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
