apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: slack-client-issue-labeled
  namespace: gh-connector
  labels:
    app: github-connector
    function: gh-connector-slack-client
    event: issueevent
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: mp-sap-github-connector
      type: issuesevent.labeled
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: gc-slack-client
      namespace: gh-connector
