apiVersion: v1
kind: ConfigMap
metadata:
  name: gc-webhook-gateway-config
  namespace: gh-connector
  labels:
    app: github-connector
    type: webhook-gateway
data:
  kymaEventsService: "http://mp-sap-github-connector-event-service.kyma-integration:8081/github-connector/v1/events"
  ghGatewayPodPort: "8081"
