kind: Service
apiVersion: v1
metadata:
  name: gc-webhook-gateway
  namespace: gh-connector
  labels:
    app: github-connector
    type: webhook-gateway
spec:
  selector:
    app: github-connector
    type: webhook-gateway
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
