apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  labels:
    function: gc-slack-client
    app: slack-connector
    serviceBinding: slack-connector
  name: gc-slack-client
  namespace: gh-connector
spec:
  serviceBindingRef:
    name: slack-connector
  usedBy:
    kind: serverless-function
    name: gc-slack-client
  parameters:
    envPrefix:
      name: "KYMA_SLACK_"