apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-webhook-gateway
  namespace: gh-connector
  labels:
    app: github-connector
    type: webhook-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-connector
      type: webhook-gateway
  template:
    metadata:
      labels:
        app: github-connector
        type: webhook-gateway
    spec:
      containers:
      - name: webhookgateway
        image: eu.gcr.io/sap-kyma-neighbors-dev/ghwebhookgateway:1.0.2
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        ports:
        - containerPort: 8081
        env:
        - name: GITHUB_CONNECTOR_NAME
          value: sap-github-webhook
        - name: EVENTING_PORT
          valueFrom:
            configMapKeyRef:
              name: gc-webhook-gateway-config
              key: ghGatewayPodPort
        - name: GITHUB_SECRET
          valueFrom:
            secretKeyRef:
              name: ghsecret
              key: secret
        - name: EVENTING_SERVICE
          valueFrom:
            configMapKeyRef:
              name: gc-webhook-gateway-config
              key: kymaEventsService

