apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: gc-slack-client
  namespace: gh-connector
  labels:
    app: github-connector
    function: gh-connector-slack-client
spec:
  type: git
  source: gc-slack-client-repo
  reference: master
  baseDir: /slackClientFunction-debug
  env:
    - name: REQ_MB_LIMIT
      value: "10"
  runtime: python38