replicaCount: 1

image: kymaflyingseals/slack-connector:1.0.0
container:
  containerPort: 8080
  limits:
    memory: "128Mi"
    cpu: "100m"

service:
  port: 80

kymaAddress: console.ghcon.neighbors.shoot.canary.k8s-hana.ondemand.com
slackBotToken: token
workspaceName: name
slackSecret: secret
